//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuntDonator
    {
        public int Id { get; set; }
        public Nullable<int> IdDonator { get; set; }
        public string TipAnuntDonator { get; set; }
        public string Mesaj { get; set; }
        public System.DateTime DataAnunt { get; set; }
    
        public virtual Donator Donator { get; set; }
    }
}
