//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BleedifyDB : DbContext
    {
        public BleedifyDB()
            : base("name=BleedifyDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresa> Adresas { get; set; }
        public virtual DbSet<AnuntDonator> AnuntDonators { get; set; }
        public virtual DbSet<CerereMedicPacient> CerereMedicPacients { get; set; }
        public virtual DbSet<Componenta> Componentas { get; set; }
        public virtual DbSet<Donatie> Donaties { get; set; }
        public virtual DbSet<Donator> Donators { get; set; }
        public virtual DbSet<GrupaDeSange> GrupaDeSanges { get; set; }
        public virtual DbSet<InstitutieAsociata> InstitutieAsociatas { get; set; }
        public virtual DbSet<Medic> Medics { get; set; }
        public virtual DbSet<Pacient> Pacients { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Utilizator> Utilizators { get; set; }
    }
}
