//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CerereMedicPacient
    {
        public int Id { get; set; }
        public Nullable<int> IdPacient { get; set; }
        public Nullable<int> IdMedic { get; set; }
        public Nullable<int> GrupaDeSange { get; set; }
        public string TipComponenta { get; set; }
        public string Stare { get; set; }
        public System.DateTime DataDepunere { get; set; }
        public System.DateTime DataServire { get; set; }
    
        public virtual GrupaDeSange GrupaDeSange1 { get; set; }
        public virtual Medic Medic { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
