//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componenta
    {
        public int Id { get; set; }
        public string TipComponenta { get; set; }
        public int IdDonatie { get; set; }
        public System.DateTime DataDepunere { get; set; }
        public Nullable<int> IdPrimitor { get; set; }
        public string Stare { get; set; }
    
        public virtual Donatie Donatie { get; set; }
        public virtual Pacient Pacient { get; set; }
    }
}
