//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donatie()
        {
            this.Componentas = new HashSet<Componenta>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdDonator { get; set; }
        public string EtapaDonare { get; set; }
        public string MotivRefuz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Componenta> Componentas { get; set; }
        public virtual Donator Donator { get; set; }
    }
}
