//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donator()
        {
            this.AnuntDonators = new HashSet<AnuntDonator>();
            this.Donaties = new HashSet<Donatie>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUtilizator { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public System.DateTime DataDonarePosibila { get; set; }
        public Nullable<int> GrupaDeSange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuntDonator> AnuntDonators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donatie> Donaties { get; set; }
        public virtual GrupaDeSange GrupaDeSange1 { get; set; }
        public virtual Utilizator Utilizator { get; set; }
    }
}
