//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutieAsociata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitutieAsociata()
        {
            this.Donaties = new HashSet<Donatie>();
            this.Pacients = new HashSet<Pacient>();
            this.Utilizators = new HashSet<Utilizator>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Adresa { get; set; }
        public string TipInstitutie { get; set; }
        public string Nume { get; set; }
        public string NumarTelefon { get; set; }
        public string Email { get; set; }
    
        public virtual Adresa Adresa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donatie> Donaties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pacient> Pacients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizator> Utilizators { get; set; }
    }
}
