//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.CerereMedicPacients = new HashSet<CerereMedicPacient>();
            this.Componentas = new HashSet<Componenta>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public System.DateTime DataNastere { get; set; }
        public Nullable<int> GrupaDeSange { get; set; }
        public Nullable<int> InstitutieAsociata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CerereMedicPacient> CerereMedicPacients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Componenta> Componentas { get; set; }
        public virtual GrupaDeSange GrupaDeSange1 { get; set; }
        public virtual InstitutieAsociata InstitutieAsociata1 { get; set; }
    }
}
