//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleedifyModels.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public new int Id { get; set; }
        public Nullable<int> IdUtilizator { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
    }
}
